[package]
name = "file_server"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = { version = "0.7.7", features = ["multipart"] }
tokio = { version = "1", features = ["full"] }
hyper = { version = "1.5", features = ["server"]}

